name: Publish to Amazon S3

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_BUCKET_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_BUCKET_SECRET_KEY }}
          aws-region: eu-west-3

      - name: Upload files to aws
        shell: bash
        run: aws s3 sync ./public s3://moustapha.xyz/ --acl public-read
